language: node_js
node_js:
- 11.4
branches:
  only:
  - master
addons:
  ssh_known_hosts:
  - 165.227.17.140
before_install:
- openssl aes-256-cbc -K $encrypted_36278caba543_key -iv $encrypted_36278caba543_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
install:
- sudo apt-get update -qq
- npm ci
before-deploy:
- npm run build
deploy:
- provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/build/ $SSH_SERVER:$SSH_PROJECT_PATH
  on:
    branch: master
