language: node_js
node_js:
- 11.4
branches:
  only:
  - master
addons:
  ssh_known_hosts: 165.227.17.140
before_install:
- sudo apt-get update -qq
- openssl aes-256-cbc -K $encrypted_36278caba543_key -iv $encrypted_36278caba543_iv -in deploy_key.enc -out ./deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
- ssh -i ./deploy_key root@165.227.17.140 pwd
install:
- npm install
deploy:
- provider: script
  skip_cleanup: true
  script: npm run build && rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/build/ $SSH_SERVER:$SSH_PROJECT_PATH
  on:
    branch: master
